"""Pydantic settings for the Hetzner-side FastAPI backend.

Env vars use ICHOR_API_ prefix. Loaded from /etc/ichor/api.env at runtime
(systemd EnvironmentFile=) which is generated by the secrets Ansible role
from SOPS-decrypted infra/secrets/*.env.
"""

from __future__ import annotations

import logging
from typing import Literal

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)


class Settings(BaseSettings):
    # No env_file: production loads from systemd EnvironmentFile=/etc/ichor/api.env
    # which is exported into the process env BEFORE Python starts. This avoids the
    # `.env` file lookup pydantic-settings does in CWD (which fails with PermissionError
    # when the service user can't read CWD owner's files).
    model_config = SettingsConfigDict(
        env_prefix="ICHOR_API_",
        extra="ignore",
    )

    # --- Identity ---
    environment: Literal["development", "staging", "production"] = "production"
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"

    # --- HTTP ---
    host: str = "127.0.0.1"
    port: int = 8000
    cors_origins: list[str] = Field(default_factory=lambda: ["https://app-ichor.pages.dev"])

    # --- Datastores (loaded from Ansible vars at runtime) ---
    database_url: str = "postgresql+asyncpg://ichor:ichor@localhost:5432/ichor"
    redis_url: str = "redis://localhost:6379/0"

    # --- Tunnel to claude-runner ---
    claude_runner_url: str = ""
    """Empty by default — must be set via ICHOR_API_CLAUDE_RUNNER_URL env var to
    `https://<TUNNEL-UUID>.cfargotunnel.com` once Cloudflare Tunnel is created.
    Empty value disables Claude routing (Couche-2 falls back to Cerebras/Groq).
    Validated at startup via `validate_claude_runner_url()` (raises in production)."""
    cf_access_client_id: str = ""
    cf_access_client_secret: str = ""

    # --- Capability 5 client-tool service token (W85, ADR-077) ---
    tool_service_token: str = ""
    """Shared secret presented by the Win11 apps/ichor-mcp stdio server
    on every POST to /v1/tools/* via the `X-Ichor-Tool-Token` header.
    Empty value disables the guard (dev only) — production lifespan
    refuses to start without one. Defense-in-depth alongside the
    Cloudflare Access JWT on the edge (PRE-1)."""

    # --- EU AI Act §50.2 watermark middleware (W88, ADR-079) ---
    ai_watermarked_route_prefixes: list[str] = Field(
        default_factory=lambda: [
            "/v1/briefings",
            "/v1/sessions",
            "/v1/post-mortems",
            "/v1/today",
            "/v1/scenarios",
        ]
    )
    """Path prefixes whose responses get the X-Ichor-AI-* watermark
    headers. Must enumerate every route that surfaces LLM-derived
    content. Pure-data collector routes (/v1/market, /v1/fred, ...)
    stay OUT. EU AI Act Article 50(2) deadline = 2026-08-02."""

    ai_provider_tag: str = "anthropic-claude-opus-4-7"
    """Identifier surfaced via X-Ichor-AI-Provider. Bumped on model
    upgrade (each upgrade also gets an ADR per ADR-029 §Cons)."""

    ai_disclosure_url: str = "https://app-ichor.pages.dev/legal/ai-disclosure"
    """URL surfaced via X-Ichor-AI-Disclosure. Must resolve to a
    human-readable disclosure page (EU AI Act §50.5 — clear and
    distinguishable, with WCAG-accessible content)."""

    # --- LLM providers (Couche 2 24/7) ---
    cerebras_api_key: str = ""
    groq_api_key: str = ""

    # --- Audio TTS ---
    azure_speech_key: str = ""
    azure_speech_region: str = "westeurope"

    # --- Data feeds ---
    fred_api_key: str = ""
    oanda_api_token: str = ""
    oanda_account_id: str = ""
    polygon_api_key: str = ""
    """Polygon.io Starter ($29/mo). Used for 1-min intraday OHLCV on
    the 8 Phase-1 assets (FX, indices, gold). REST endpoint :
    https://api.polygon.io/v2/aggs/ticker/{ticker}/range/1/minute/...
    """

    flashalpha_api_key: str = ""
    """FlashAlpha API key. Free tier = 5 req/day, single-name stocks
    only with `?expiration=YYYY-MM-DD` filter. Index/ETF GEX (SPX/NDX/
    SPY/QQQ — what Ichor actually wants) requires Basic+ paid plan.
    Empty = collector skipped silently. See ADR-022 for the GEX strategy
    fallback (yfinance-derived dealer GEX estimator)."""

    finra_api_token: str = ""
    """FINRA Data API Bearer token. Optional — public endpoints work
    without auth for our daily polling cadence. Token raises rate
    limits on the otcMarket/regShoDaily + consolidatedShortInterest
    datasets when we eventually hit the unauth ceiling."""

    bls_api_key: str = ""
    """BLS Public Data API key. Optional — free tier is 25 q/day
    no-key, 500 q/day with a registered key. Empty means we use the
    no-key endpoint (sufficient for our 5-series daily poll = ~5/day)."""

    eia_api_key: str = ""
    """EIA OpenData v2 API key. REQUIRED for petroleum + STEO
    collectors (no anonymous tier). Free registration at
    https://www.eia.gov/opendata/register.php. Empty = collector
    skipped silently."""

    bluesky_app_password: str = ""
    """Bluesky App Password for the search endpoint (free, 2026).
    Empty means we restrict to public author-feed scraping (no
    search) which is the default. Format : `xxxx-xxxx-xxxx-xxxx`."""

    bluesky_identifier: str = ""
    """Bluesky handle linked to the App Password. Required only if
    bluesky_app_password is set."""

    # --- PWA push (VAPID) ---
    vapid_public_key: str = ""
    """Base64url-encoded VAPID public key. Exposed to the front-end
    via GET /v1/push/public-key so the service worker can register
    a Push subscription."""
    vapid_private_key: str = ""
    """Base64url-encoded VAPID private key. Used by pywebpush to sign
    push notifications. NEVER expose to clients."""
    vapid_contact: str = "mailto:admin@ichor.local"
    """RFC 8292 audience claim — admin email or https URL."""

    # --- Observability (Loki/Langfuse) ---
    loki_endpoint: str = "http://127.0.0.1:3100"
    langfuse_public_key: str = ""
    langfuse_secret_key: str = ""
    langfuse_host: str = "http://127.0.0.1:3000"

    # --- Briefing assembly (ADR-083 D1 — 6-asset universe verrouillé) ---
    briefing_assets: list[str] = Field(
        default_factory=lambda: [
            "EUR_USD",
            "GBP_USD",
            "USD_CAD",
            "XAU_USD",
            "NAS100_USD",
            "SPX500_USD",
        ]
    )
    """The 6 assets Eliot actually trades (verbatim 2026-05-11 + ADR-083 D1).
    USDJPY + AUDUSD are tracked-no-card : their ticker maps remain wired in
    data_pool (so they can be queried explicitly via --assets) but the
    autonomous batch + cron briefings only emit cards for these 6. Pre-W104
    this was split into briefing_assets_p1 + briefing_assets_p2 with
    pre_londres receiving only p1 — GBP and CAD therefore received 3
    cards/jour instead of 4 (audit G1 — closed W104a)."""

    # --- Mastodon followed feeds ---
    # CSV-encoded list of `kind:instance:handle` triples, e.g.
    #   "user:mastodon.social:alice,tag:econtwitter.net:macroeconomics".
    # Empty = collector no-ops (cron timer can register but skip).
    # Each entry expands to https://{instance}/users/{handle}.atom
    # (kind=user) or https://{instance}/tags/{handle}.atom (kind=tag).
    mastodon_followed_feeds: str = ""
    """Comma-separated list of `kind:instance:handle` triples.
    Example : "user:mastodon.social:bopp,tag:econtwitter.net:fomc".
    Read by `cli.run_mastodon_collector` to enumerate the feeds to fetch.
    """

    @model_validator(mode="after")
    def validate_claude_runner_url(self) -> Settings:
        """Warn (or raise in production) when the Claude runner URL is unset.

        Behavior:
          - production + empty url    → raise ValueError (boot fails fast)
          - non-production + empty    → log warning, allow continue
          - placeholder.cfargotunnel  → raise (legacy bug #6 fingerprint)
        """
        url = self.claude_runner_url.strip()
        if "placeholder.cfargotunnel.com" in url:
            raise ValueError(
                "ICHOR_API_CLAUDE_RUNNER_URL still points at the legacy "
                "placeholder. Set it to https://<TUNNEL-UUID>.cfargotunnel.com."
            )
        if not url:
            if self.environment == "production":
                raise ValueError(
                    "ICHOR_API_CLAUDE_RUNNER_URL is required in production. "
                    "Couche-2 routing (CB-NLP, News-NLP, Sentiment, Positioning) "
                    "would fall back to Cerebras/Groq silently otherwise."
                )
            logger.warning(
                "claude_runner_url is empty — Couche-2 will fall back to "
                "Cerebras/Groq. Acceptable in development; required in production."
            )
        return self


_settings: Settings | None = None


def get_settings() -> Settings:
    global _settings
    if _settings is None:
        _settings = Settings()
    return _settings
