"""Pydantic settings for the Hetzner-side FastAPI backend.

Env vars use ICHOR_API_ prefix. Loaded from /etc/ichor/api.env at runtime
(systemd EnvironmentFile=) which is generated by the secrets Ansible role
from SOPS-decrypted infra/secrets/*.env.
"""

from __future__ import annotations

from typing import Literal

from pydantic import Field, PostgresDsn, RedisDsn
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # No env_file: production loads from systemd EnvironmentFile=/etc/ichor/api.env
    # which is exported into the process env BEFORE Python starts. This avoids the
    # `.env` file lookup pydantic-settings does in CWD (which fails with PermissionError
    # when the service user can't read CWD owner's files).
    model_config = SettingsConfigDict(
        env_prefix="ICHOR_API_",
        extra="ignore",
    )

    # --- Identity ---
    environment: Literal["development", "staging", "production"] = "production"
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"

    # --- HTTP ---
    host: str = "127.0.0.1"
    port: int = 8000
    cors_origins: list[str] = Field(default_factory=lambda: ["https://app-ichor.pages.dev"])

    # --- Datastores (loaded from Ansible vars at runtime) ---
    database_url: str = "postgresql+asyncpg://ichor:ichor@localhost:5432/ichor"
    redis_url: str = "redis://localhost:6379/0"

    # --- Tunnel to claude-runner ---
    claude_runner_url: str = "https://placeholder.cfargotunnel.com"
    """Set to <TUNNEL-UUID>.cfargotunnel.com after CF Tunnel created."""
    cf_access_client_id: str = ""
    cf_access_client_secret: str = ""

    # --- LLM providers (Couche 2 24/7) ---
    cerebras_api_key: str = ""
    groq_api_key: str = ""

    # --- Audio TTS ---
    azure_speech_key: str = ""
    azure_speech_region: str = "westeurope"

    # --- Data feeds ---
    fred_api_key: str = ""
    oanda_api_token: str = ""
    oanda_account_id: str = ""
    polygon_api_key: str = ""
    """Polygon.io Starter ($29/mo). Used for 1-min intraday OHLCV on
    the 8 Phase-1 assets (FX, indices, gold). REST endpoint :
    https://api.polygon.io/v2/aggs/ticker/{ticker}/range/1/minute/...
    """

    flashalpha_api_key: str = ""
    """FlashAlpha free-tier key (5 req/day). Used for SPX + NDX dealer
    GEX, gamma_flip, call_wall, put_wall snapshots. Empty = collector
    skipped silently."""

    # --- PWA push (VAPID) ---
    vapid_public_key: str = ""
    """Base64url-encoded VAPID public key. Exposed to the front-end
    via GET /v1/push/public-key so the service worker can register
    a Push subscription."""
    vapid_private_key: str = ""
    """Base64url-encoded VAPID private key. Used by pywebpush to sign
    push notifications. NEVER expose to clients."""
    vapid_contact: str = "mailto:admin@ichor.local"
    """RFC 8292 audience claim — admin email or https URL."""

    # --- Observability (Loki/Langfuse) ---
    loki_endpoint: str = "http://127.0.0.1:3100"
    langfuse_public_key: str = ""
    langfuse_secret_key: str = ""
    langfuse_host: str = "http://127.0.0.1:3000"

    # --- Briefing assembly ---
    briefing_assets_p1: list[str] = Field(
        default_factory=lambda: ["EUR_USD", "XAU_USD", "NAS100_USD", "USD_JPY", "SPX500_USD"]
    )
    briefing_assets_p2: list[str] = Field(
        default_factory=lambda: ["GBP_USD", "AUD_USD", "USD_CAD"]
    )


_settings: Settings | None = None


def get_settings() -> Settings:
    global _settings
    if _settings is None:
        _settings = Settings()
    return _settings
