// EU AI Act Article 50 §1 + §5 — disclosure banner.
//
// Article 50 §1 : when a user interacts with an AI system, they must be
// informed of that fact. §5 : disclosure must be "clear and distinguishable"
// at the latest at the first interaction. Permanent (not dismissible) because
// fresh AI-generated reads appear every session ; non-blocking.
//
// Vision §6.9 : never name the model nor any version on the page — so the
// banner discloses "generated by AI" generically, and links to the
// transparency page rather than a separate methodology surface (§9.5).
//
// Reference: ADR-029 (EU AI Act §50 + AMF DOC-2008-23 disclosure).

export function AIDisclosureBanner() {
  return (
    <aside
      role="note"
      aria-label="Information IA"
      className="sticky top-0 z-40 border-b border-[var(--glass-border)] bg-[var(--color-bg-elevated)]/95 backdrop-blur-sm"
    >
      {/* min-h-[28px] satisfies WCAG 2.2 §2.5.8 Target Size on the only
        interactive element (the transparency link). */}
      <div className="mx-auto flex min-h-[28px] max-w-7xl items-center justify-between gap-3 px-4 py-1 font-mono text-[11px]">
        <span className="flex items-center gap-2 text-[var(--color-text-secondary)]">
          <span
            aria-hidden="true"
            className="inline-flex h-1.5 w-1.5 rounded-full"
            style={{ backgroundColor: "var(--accent)" }}
          />
          <span className="uppercase tracking-widest text-[var(--color-text-muted)]">
            Analyse générée par IA
          </span>
          <span className="hidden sm:inline">
            aide à la décision — jamais un conseil humain, ni un signal d&apos;achat ou de vente.
          </span>
        </span>
        <a
          href="/legal/ai-disclosure"
          className="inline-flex min-h-[24px] items-center px-1 text-[var(--accent)] underline underline-offset-2 hover:text-[var(--color-text-primary)]"
        >
          transparence →
        </a>
      </div>
    </aside>
  );
}
