"""Critic Agent — sober reviewer of every Ichor briefing.

Per the ARCHITECTURE_FINALE Phase 1 deliverable (and Eliot's "best
trader in the world" honesty rule), every Ichor briefing must be
reviewed by an independent Critic Agent BEFORE publication.

Workflow :
  1. Briefing markdown is generated by Claude (Voie D, Max 20x).
  2. Same source pool used to assemble the original context is passed
     to the Critic.
  3. Critic returns a `CriticVerdict` :
       - approved      : ship as-is
       - amendments    : ship with suggested redactions / footer
       - blocked       : do NOT ship — material hallucination, retry

The Critic is itself a Claude prompt (no third-party LLM here — Voie D)
but kept SHORT and structured so it's cheap and auditable. Output is
strict JSON.

PAPER-friendly. The Critic itself does not generate orders. It only
gates briefings before they reach the dashboard / TTS.
"""

from .reviewer import (
    CriticVerdict,
    Verdict,
    review_briefing,
    HallucinationFinding,
)

__all__ = [
    "CriticVerdict",
    "Verdict",
    "review_briefing",
    "HallucinationFinding",
]
